name: Health Check Script

on:
  push:
    branches:
      - main
  workflow_dispatch:  # permite declanșarea manuală din GitHub UI

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run health check script
      run: python scripts/health_check.py
